name: experiments
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch=2.1.2
  - scikit-learn=1.3.0
  - pandas=1.5.3
  - matplotlib=3.7.1
  - networkx=3.1
  pip:
    - numpy==1.25.2
    - multiprocess==0.70.15
